M48
; DRILL file KiCad 10.0.4 date 2026-07-08T20:03:10
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-08T20:03:10+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.250
%
G90
G05
T1
X12.61Y-91.9
X18.39Y-91.9
T2
X37.5Y-94.5
X43.0Y-94.5
X48.5Y-94.5
X54.0Y-94.5
T3
X78.71Y-86.46
X84.21Y-86.46
X107.16Y-86.46
X112.66Y-86.46
M30
